name: parkflow
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  crypto: ^3.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_svg: ^0.22.0
  google_nav_bar: ^5.0.6
  latlong2: ^0.8.1
  provider: ^6.0.5
  uuid: ^3.0.7
  intl: ^0.17.0
  geolocator: ^9.0.2
  osm_nominatim: ^2.0.1
  geocoding: ^2.1.0
  rxdart: ^0.27.7
  flutter_pw_validator: ^1.5.0
  flutter_map_location_marker: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/usericon.svg
    - assets/vehicle_brands_icons/audi.svg
    - assets/vehicle_brands_icons/bmw.svg
    - assets/vehicle_brands_icons/citroen.svg
    - assets/vehicle_brands_icons/ford.svg
    - assets/vehicle_brands_icons/honda.svg
    - assets/vehicle_brands_icons/mercedes.svg
    - assets/vehicle_brands_icons/porsche.svg
    - assets/vehicle_brands_icons/renault.svg
    - assets/vehicle_brands_icons/toyota.svg
    - assets/vehicle_brands_icons/volkswagen.svg
    - assets/vehicle_brands_icons/default.svg
